name: Build and upload

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install packages
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: |
            npm ci

      - name: Build code
        run: |
          npm run build

      - name: Zip build
        uses: vimtor/action-zip@v1.2
        with:
          files: dist/
          dest: dist.zip

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: dist.zip
          path: ./dist.zip
          if-no-files-found: error
